# Generated by Django 4.1.2 on 2022-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('images', models.CharField(max_length=2500)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
